name: Algos
description: A collection of Data Structures + Algorithms concepts and questions!
meta_description: "A collection of Data Structures + Algorithms concepts and questions!"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://algorithms.surge.sh/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://algorithms.surge.sh/'
author:         'Ahsan Azim'

# excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
